modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TeamBR-Modding/Nucleus/issues"

[[mods]]
  modId="nucleus_teambr"
  namespace="nucleus"
  version="${version}"
  displayName="Nucleus"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/nucleus"
  authors="pauljoda, Dyonovan"
  description='''
  Library to help with TeamBR mods
  '''
