modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/pauljoda/Nucleus/issues"
license="http://creativecommons.org/licenses/by-nc-sa/4.0/"
[[mods]]
  modId="nucleus_pauljoda"
  namespace="pauljoda"
  version="2.0"
  displayName="Nucleus"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/nucleus"
  authors="pauljoda, Dyonovan"
  description='''
  Library to help with pauljoda mods
  '''
