# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ 1.16.2 ]
  pull_request:
    branches: [ 1.16.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create Known Hosts
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build uploadArchives
      env:
        ftp_password: ${{ secrets.FTP_PASSWORD }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/Nucleus/Nucleus/build/libs/*

